- name: Install nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.3/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: Install node
  become: no
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }} && nvm use {{ item }} && nvm alias default {{ item }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
  loop:
    - 18
