on:
  pull_request:
jobs:
  build_admin:
    name: Build admin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install dependencies
      run: npm ci
      working-directory: admin
    - name: Lint
      working-directory: admin
      run: |
        npm run lint
    - name: Format
      working-directory: admin
      run: |
        npm run format
    - name: Build
      working-directory: admin
      run: |
        npm run build
